name: DieQuietly
version: '${version}'
main: joshdev.diequietly.DieQuietly
api-version: '1.20'
commands:
  toggledeathmsgs:
    description: Toggles death messages
    usage: /<command>
    aliases: [tdm]